// Video transcripts — server-side only, via YouTube's UNOFFICIAL, UNDOCUMENTED `timedtext`
// endpoint (`https://www.youtube.com/api/timedtext`). This is a deliberate, KNOWN DEVIATION from
// this project's usual API-only posture:
//
//   - The official Data API's `captions.download` requires the UPLOADER's own OAuth token — it
//     cannot serve a third party's captions for someone else's video, so it is not usable here.
//   - The IFrame Player's own caption rendering is UI-only; there is no supported way to pull the
//     raw cue text out of it for a text panel.
//   - `timedtext` is the same risk class as the UULF playlist-prefix convention used elsewhere in
//     this codebase (undocumented, reverse-engineered, may change or break without notice) — but
//     a step further: unlike a documented API called for its intended purpose, this is closer to
//     scraping a page's own internal data endpoint. That is the same category of access this
//     project's own compliance posture describes as impermissible elsewhere.
//
// ACCEPTED KNOWINGLY, for this feature only, on these terms: personal use, low volume (one fetch
// per video the user actually opens a transcript for, aggressively cached — see
// transcriptCache.ts), never redistributed, and it fails soft everywhere (a broken/changed
// response NEVER breaks the watch page — see getTranscript's catch-all below). If this endpoint
// ever disappears or starts refusing requests, the correct response is to remove the feature, not
// route around whatever blocks it.
import "server-only";
import { z } from "zod";
import { XMLParser } from "fast-xml-parser";

const TIMEDTEXT_BASE = "https://www.youtube.com/api/timedtext";
const xmlParser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: "@_" });

export type TranscriptTrack = {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
};

export type TranscriptCue = {
  startMs: number;
  durMs: number;
  text: string;
};

export type TranscriptResult =
  | { available: false }
  | { available: true; languageCode: string; tracks: TranscriptTrack[]; cues: TranscriptCue[] };

// --- Pure parsing (unit-testable without any network — fed the parser's own output) ----------

const TrackListXmlSchema = z.object({
  transcript_list: z
    .object({
      track: z.union([z.record(z.string(), z.unknown()), z.array(z.record(z.string(), z.unknown()))]).optional(),
    })
    .optional(),
});

/** Parse the `type=list` track-list XML (already run through fast-xml-parser) into tracks. */
export function parseTrackListXml(parsed: unknown): TranscriptTrack[] {
  const result = TrackListXmlSchema.safeParse(parsed);
  if (!result.success) return [];
  const raw = result.data.transcript_list?.track;
  if (!raw) return [];
  const rows = Array.isArray(raw) ? raw : [raw];
  return rows
    .map((row) => {
      const langCode = row["@_lang_code"];
      if (typeof langCode !== "string" || !langCode) return null;
      const name = row["@_lang_translated"] ?? row["@_lang_original"] ?? row["@_name"];
      return {
        languageCode: langCode,
        languageName: typeof name === "string" && name ? name : langCode,
        isAutoGenerated: row["@_kind"] === "asr",
      } satisfies TranscriptTrack;
    })
    .filter((t): t is TranscriptTrack => t !== null);
}

const Json3Schema = z.object({
  events: z
    .array(
      z.object({
        tStartMs: z.number().optional(),
        dDurationMs: z.number().optional(),
        segs: z.array(z.object({ utf8: z.string().optional() })).optional(),
      }),
    )
    .optional(),
});

/** Parse the `fmt=json3` transcript body (already `JSON.parse`d) into cues. */
export function parseJson3Cues(parsed: unknown): TranscriptCue[] {
  const result = Json3Schema.safeParse(parsed);
  if (!result.success) return [];
  const events = result.data.events ?? [];
  return events
    .map((ev) => {
      const text = (ev.segs ?? []).map((s) => s.utf8 ?? "").join("");
      if (!text.trim()) return null;
      return { startMs: ev.tStartMs ?? 0, durMs: ev.dDurationMs ?? 0, text } satisfies TranscriptCue;
    })
    .filter((c): c is TranscriptCue => c !== null);
}

const LegacyXmlSchema = z.object({
  transcript: z
    .object({
      text: z
        .union([z.record(z.string(), z.unknown()), z.array(z.record(z.string(), z.unknown()))])
        .optional(),
    })
    .optional(),
});

/** Parse the legacy plain-XML transcript body (fallback when json3 isn't available) into cues. */
export function parseLegacyXmlCues(parsed: unknown): TranscriptCue[] {
  const result = LegacyXmlSchema.safeParse(parsed);
  if (!result.success) return [];
  const raw = result.data.transcript?.text;
  if (!raw) return [];
  const rows = Array.isArray(raw) ? raw : [raw];
  return rows
    .map((row) => {
      const text = row["#text"];
      if (typeof text !== "string" || !text.trim()) return null;
      const start = Number(row["@_start"]);
      const dur = Number(row["@_dur"]);
      return {
        startMs: Number.isFinite(start) ? Math.round(start * 1000) : 0,
        durMs: Number.isFinite(dur) ? Math.round(dur * 1000) : 0,
        text,
      } satisfies TranscriptCue;
    })
    .filter((c): c is TranscriptCue => c !== null);
}

/** Pick the track to serve: the requested language if present, else the default/first track. */
export function pickTrack(tracks: TranscriptTrack[], requestedLang?: string): TranscriptTrack | null {
  if (tracks.length === 0) return null;
  if (requestedLang) {
    const match = tracks.find((t) => t.languageCode === requestedLang);
    if (match) return match;
  }
  return tracks[0];
}

// --- I/O orchestration (server-only fetches, NOT covered by unit tests — the parsing above is) --

const FETCH_TIMEOUT_MS = 8000;

async function fetchWithTimeout(url: string): Promise<Response | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: controller.signal, cache: "no-store" });
    return res.ok ? res : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Fetch a video's transcript for `lang` (or its default track if omitted). NO CAPTIONS AVAILABLE
 * is a normal, expected outcome (`{available: false}`) — most videos have none, and that is not
 * an error. Any network failure, timeout, or response-shape change also fails soft to
 * `{available: false}` rather than throwing — the watch page must never break because of this.
 */
export async function getTranscript(videoId: string, lang?: string): Promise<TranscriptResult> {
  try {
    const listRes = await fetchWithTimeout(
      `${TIMEDTEXT_BASE}?type=list&v=${encodeURIComponent(videoId)}`,
    );
    if (!listRes) return { available: false };
    const listXml = await listRes.text();
    const tracks = parseTrackListXml(xmlParser.parse(listXml));
    const track = pickTrack(tracks, lang);
    if (!track) return { available: false };

    const json3Res = await fetchWithTimeout(
      `${TIMEDTEXT_BASE}?v=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(track.languageCode)}&fmt=json3`,
    );
    if (json3Res) {
      const body = await json3Res.text();
      try {
        const cues = parseJson3Cues(JSON.parse(body));
        if (cues.length > 0) {
          return { available: true, languageCode: track.languageCode, tracks, cues };
        }
      } catch {
        /* malformed json3 — fall through to the legacy XML format below */
      }
    }

    const legacyRes = await fetchWithTimeout(
      `${TIMEDTEXT_BASE}?v=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(track.languageCode)}`,
    );
    if (!legacyRes) return { available: false };
    const legacyXml = await legacyRes.text();
    const cues = parseLegacyXmlCues(xmlParser.parse(legacyXml));
    if (cues.length === 0) return { available: false };
    return { available: true, languageCode: track.languageCode, tracks, cues };
  } catch {
    return { available: false };
  }
}
