import { describe, it, expect, beforeEach, vi } from "vitest";
import { XMLParser } from "fast-xml-parser";

// transcript.ts/transcriptCache.ts are server-only modules; stub the import marker so their
// pure parsing/cache functions can be unit-tested in the node test environment (same convention
// as youtube.test.ts).
vi.mock("server-only", () => ({}));

import {
  parseTrackListXml,
  parseJson3Cues,
  parseLegacyXmlCues,
  pickTrack,
} from "../src/lib/transcript";
import {
  clearTranscriptCache,
  getCachedTranscript,
  setCachedTranscript,
  transcriptCacheKey,
} from "../src/lib/transcriptCache";

const xmlParser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: "@_" });

describe("parseTrackListXml — the type=list track-list response", () => {
  it("parses multiple tracks, flagging auto-generated (kind=asr) ones", () => {
    const xml = `<transcript_list>
      <track id="0" lang_code="en" lang_original="English" lang_translated="English" lang_default="true"/>
      <track id="1" lang_code="ar" lang_original="Arabic" lang_translated="Arabic" kind="asr"/>
    </transcript_list>`;
    const tracks = parseTrackListXml(xmlParser.parse(xml));
    expect(tracks).toEqual([
      { languageCode: "en", languageName: "English", isAutoGenerated: false },
      { languageCode: "ar", languageName: "Arabic", isAutoGenerated: true },
    ]);
  });

  it("parses a single track (fast-xml-parser doesn't wrap a lone element in an array)", () => {
    const xml = `<transcript_list><track id="0" lang_code="en" lang_original="English"/></transcript_list>`;
    const tracks = parseTrackListXml(xmlParser.parse(xml));
    expect(tracks).toEqual([{ languageCode: "en", languageName: "English", isAutoGenerated: false }]);
  });

  it("NO CAPTIONS is a normal outcome — an empty list yields an empty array, not an error", () => {
    const xml = `<transcript_list></transcript_list>`;
    expect(parseTrackListXml(xmlParser.parse(xml))).toEqual([]);
  });

  it("never throws on a garbage/unrelated shape — returns []", () => {
    expect(parseTrackListXml({ somethingElse: true })).toEqual([]);
    expect(parseTrackListXml(null)).toEqual([]);
    expect(parseTrackListXml("not even an object")).toEqual([]);
    expect(parseTrackListXml(xmlParser.parse("<totally><unrelated/></totally>"))).toEqual([]);
  });

  it("skips a track row missing lang_code rather than fabricating one", () => {
    const xml = `<transcript_list><track id="0" lang_original="English"/></transcript_list>`;
    expect(parseTrackListXml(xmlParser.parse(xml))).toEqual([]);
  });
});

describe("parseJson3Cues — the fmt=json3 transcript body", () => {
  it("joins multi-segment events into one cue's text", () => {
    const body = {
      events: [
        { tStartMs: 0, dDurationMs: 1500, segs: [{ utf8: "Hello " }, { utf8: "world" }] },
        { tStartMs: 1500, dDurationMs: 2000, segs: [{ utf8: "Second line" }] },
      ],
    };
    expect(parseJson3Cues(body)).toEqual([
      { startMs: 0, durMs: 1500, text: "Hello world" },
      { startMs: 1500, durMs: 2000, text: "Second line" },
    ]);
  });

  it("drops position-only events with no actual text (a real json3 quirk)", () => {
    const body = { events: [{ tStartMs: 0, dDurationMs: 100 }, { tStartMs: 100, dDurationMs: 100, segs: [{ utf8: "  " }] }] };
    expect(parseJson3Cues(body)).toEqual([]);
  });

  it("never throws on a malformed body — returns []", () => {
    expect(parseJson3Cues(null)).toEqual([]);
    expect(parseJson3Cues("not an object")).toEqual([]);
    expect(parseJson3Cues({ events: "not an array" })).toEqual([]);
    expect(parseJson3Cues({ wireMagic: "pb3" })).toEqual([]);
  });
});

describe("parseLegacyXmlCues — the plain-XML transcript fallback format", () => {
  it("parses start/dur in seconds into millisecond cues", () => {
    const xml = `<transcript><text start="0.5" dur="2.3">Hello there</text><text start="2.8" dur="1.1">Second</text></transcript>`;
    expect(parseLegacyXmlCues(xmlParser.parse(xml))).toEqual([
      { startMs: 500, durMs: 2300, text: "Hello there" },
      { startMs: 2800, durMs: 1100, text: "Second" },
    ]);
  });

  it("never throws on a malformed/unrelated response — returns []", () => {
    expect(parseLegacyXmlCues(null)).toEqual([]);
    expect(parseLegacyXmlCues(xmlParser.parse("<unrelated/>"))).toEqual([]);
  });

  it("skips blank-text rows", () => {
    const xml = `<transcript><text start="0" dur="1">   </text></transcript>`;
    expect(parseLegacyXmlCues(xmlParser.parse(xml))).toEqual([]);
  });
});

describe("pickTrack — track selection", () => {
  const tracks = [
    { languageCode: "en", languageName: "English", isAutoGenerated: false },
    { languageCode: "ar", languageName: "Arabic", isAutoGenerated: true },
  ];

  it("returns the requested language if present", () => {
    expect(pickTrack(tracks, "ar")?.languageCode).toBe("ar");
  });

  it("falls back to the first/default track when no language is requested", () => {
    expect(pickTrack(tracks)?.languageCode).toBe("en");
  });

  it("falls back to the first track when the requested language isn't available", () => {
    expect(pickTrack(tracks, "fr")?.languageCode).toBe("en");
  });

  it("returns null for an empty track list — NO CAPTIONS AVAILABLE, not an error", () => {
    expect(pickTrack([])).toBeNull();
  });
});

describe("transcriptCache — permanent, keyed by (videoId, lang)", () => {
  beforeEach(() => {
    clearTranscriptCache();
  });

  it("caches and retrieves a real transcript result", () => {
    const result = {
      available: true as const,
      languageCode: "en",
      tracks: [{ languageCode: "en", languageName: "English", isAutoGenerated: false }],
      cues: [{ startMs: 0, durMs: 100, text: "hi" }],
    };
    const key = transcriptCacheKey("abc12345678", "en");
    setCachedTranscript(key, result);
    expect(getCachedTranscript(key)).toEqual(result);
  });

  it("also caches a NEGATIVE result (no captions) — avoids re-hammering the endpoint for a permanently-empty video", () => {
    const key = transcriptCacheKey("noCaptions1");
    setCachedTranscript(key, { available: false });
    expect(getCachedTranscript(key)).toEqual({ available: false });
  });

  it("different languages for the same video get distinct cache entries", () => {
    const enKey = transcriptCacheKey("sameVideo12", "en");
    const arKey = transcriptCacheKey("sameVideo12", "ar");
    expect(enKey).not.toBe(arKey);
    setCachedTranscript(enKey, { available: false });
    expect(getCachedTranscript(arKey)).toBeUndefined();
  });

  it("a miss returns undefined, not a thrown error", () => {
    expect(getCachedTranscript(transcriptCacheKey("neverFetched"))).toBeUndefined();
  });
});
