import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { XMLParser } from "fast-xml-parser";

// transcript.ts/transcriptCache.ts are server-only modules; stub the import marker so their
// pure parsing/cache functions can be unit-tested in the node test environment (same convention
// as youtube.test.ts).
vi.mock("server-only", () => ({}));

import {
  parseTrackListXml,
  parseJson3Cues,
  parseLegacyXmlCues,
  pickTrack,
} from "../src/lib/transcript";
import {
  bustCachedTranscript,
  clearTranscriptCache,
  getCachedTranscript,
  setCachedTranscript,
  transcriptCacheKey,
} from "../src/lib/transcriptCache";

const xmlParser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: "@_" });

describe("parseTrackListXml — the type=list track-list response", () => {
  it("parses multiple tracks, flagging auto-generated (kind=asr) ones", () => {
    const xml = `<transcript_list>
      <track id="0" lang_code="en" lang_original="English" lang_translated="English" lang_default="true"/>
      <track id="1" lang_code="ar" lang_original="Arabic" lang_translated="Arabic" kind="asr"/>
    </transcript_list>`;
    const result = parseTrackListXml(xmlParser.parse(xml));
    expect(result).toEqual({
      rootPresent: true,
      tracks: [
        { languageCode: "en", languageName: "English", isAutoGenerated: false },
        { languageCode: "ar", languageName: "Arabic", isAutoGenerated: true },
      ],
    });
  });

  it("parses a single track (fast-xml-parser doesn't wrap a lone element in an array)", () => {
    const xml = `<transcript_list><track id="0" lang_code="en" lang_original="English"/></transcript_list>`;
    const result = parseTrackListXml(xmlParser.parse(xml));
    expect(result).toEqual({
      rootPresent: true,
      tracks: [{ languageCode: "en", languageName: "English", isAutoGenerated: false }],
    });
  });

  it("a genuinely-empty list (root present, no <track> children) is a CONFIRMED absence, not an error", () => {
    const xml = `<transcript_list></transcript_list>`;
    expect(parseTrackListXml(xmlParser.parse(xml))).toEqual({ rootPresent: true, tracks: [] });
  });

  it("REGRESSION (the false-negative bug): an EMPTY response body — fast-xml-parser's `{}` for '' — is NOT treated as a confirmed empty list", () => {
    // This is the exact shape a degraded/rate-limited timedtext response produces: HTTP 200,
    // zero-byte body. It must be distinguishable from a real `<transcript_list></transcript_list>`
    // so it never gets cached as "this video has no captions".
    expect(parseTrackListXml(xmlParser.parse(""))).toEqual({ rootPresent: false });
  });

  it("an unrelated/garbage shape with no transcript_list root is also NOT rootPresent", () => {
    expect(parseTrackListXml({ somethingElse: true })).toEqual({ rootPresent: false });
    expect(parseTrackListXml(null)).toEqual({ rootPresent: false });
    expect(parseTrackListXml("not even an object")).toEqual({ rootPresent: false });
    expect(parseTrackListXml(xmlParser.parse("<totally><unrelated/></totally>"))).toEqual({
      rootPresent: false,
    });
  });

  it("skips a track row missing lang_code rather than fabricating one", () => {
    const xml = `<transcript_list><track id="0" lang_original="English"/></transcript_list>`;
    expect(parseTrackListXml(xmlParser.parse(xml))).toEqual({ rootPresent: true, tracks: [] });
  });
});

describe("parseJson3Cues — the fmt=json3 transcript body", () => {
  it("joins multi-segment events into one cue's text", () => {
    const body = {
      events: [
        { tStartMs: 0, dDurationMs: 1500, segs: [{ utf8: "Hello " }, { utf8: "world" }] },
        { tStartMs: 1500, dDurationMs: 2000, segs: [{ utf8: "Second line" }] },
      ],
    };
    expect(parseJson3Cues(body)).toEqual([
      { startMs: 0, durMs: 1500, text: "Hello world" },
      { startMs: 1500, durMs: 2000, text: "Second line" },
    ]);
  });

  it("drops position-only events with no actual text (a real json3 quirk)", () => {
    const body = { events: [{ tStartMs: 0, dDurationMs: 100 }, { tStartMs: 100, dDurationMs: 100, segs: [{ utf8: "  " }] }] };
    expect(parseJson3Cues(body)).toEqual([]);
  });

  it("never throws on a malformed body — returns []", () => {
    expect(parseJson3Cues(null)).toEqual([]);
    expect(parseJson3Cues("not an object")).toEqual([]);
    expect(parseJson3Cues({ events: "not an array" })).toEqual([]);
    expect(parseJson3Cues({ wireMagic: "pb3" })).toEqual([]);
  });
});

describe("parseLegacyXmlCues — the plain-XML transcript fallback format", () => {
  it("parses start/dur in seconds into millisecond cues", () => {
    const xml = `<transcript><text start="0.5" dur="2.3">Hello there</text><text start="2.8" dur="1.1">Second</text></transcript>`;
    expect(parseLegacyXmlCues(xmlParser.parse(xml))).toEqual([
      { startMs: 500, durMs: 2300, text: "Hello there" },
      { startMs: 2800, durMs: 1100, text: "Second" },
    ]);
  });

  it("never throws on a malformed/unrelated response — returns []", () => {
    expect(parseLegacyXmlCues(null)).toEqual([]);
    expect(parseLegacyXmlCues(xmlParser.parse("<unrelated/>"))).toEqual([]);
  });

  it("skips blank-text rows", () => {
    const xml = `<transcript><text start="0" dur="1">   </text></transcript>`;
    expect(parseLegacyXmlCues(xmlParser.parse(xml))).toEqual([]);
  });
});

describe("pickTrack — prefers a MANUAL track over auto-generated (asr), never filters asr out entirely", () => {
  const manualEn = { languageCode: "en", languageName: "English", isAutoGenerated: false };
  const asrEn = { languageCode: "en", languageName: "English (auto)", isAutoGenerated: true };
  const asrAr = { languageCode: "ar", languageName: "Arabic", isAutoGenerated: true };

  it("prefers the manual track over an asr track in the SAME requested language", () => {
    expect(pickTrack([asrEn, manualEn], "en")).toEqual(manualEn);
  });

  it("falls back to asr when it's the ONLY track for the requested language", () => {
    expect(pickTrack([asrAr], "ar")).toEqual(asrAr);
  });

  it("a video with ONLY an asr track (the common case for most spoken-word videos) still surfaces it — never filtered out", () => {
    expect(pickTrack([asrAr])).toEqual(asrAr);
  });

  it("with no requested language, prefers the first manual track overall over any asr track", () => {
    expect(pickTrack([asrAr, manualEn])).toEqual(manualEn);
  });

  it("falls back to the first asr track when no manual track exists at all", () => {
    expect(pickTrack([asrAr, asrEn])).toEqual(asrAr);
  });

  it("an unmatched requested language still falls back to a manual track before any asr track", () => {
    expect(pickTrack([asrAr, manualEn], "fr")).toEqual(manualEn);
  });

  it("returns null for an empty track list — NO CAPTIONS AVAILABLE, not an error", () => {
    expect(pickTrack([])).toBeNull();
  });
});

describe("transcriptCache — positive results permanent, negative results TTL-bounded, failures never cached", () => {
  beforeEach(() => {
    clearTranscriptCache();
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-01T00:00:00.000Z"));
  });
  afterEach(() => {
    vi.useRealTimers();
  });

  const positive = {
    available: true as const,
    languageCode: "en",
    tracks: [{ languageCode: "en", languageName: "English", isAutoGenerated: true }],
    cues: [{ startMs: 0, durMs: 100, text: "hi" }],
  };

  it("caches and retrieves a real (positive) transcript result", () => {
    const key = transcriptCacheKey("abc12345678", "en");
    setCachedTranscript(key, positive);
    expect(getCachedTranscript(key)).toEqual(positive);
  });

  it("caches a CONFIRMED negative (no-captions) result — avoids re-hammering the endpoint for a permanently-empty video", () => {
    const key = transcriptCacheKey("noCaptions1");
    setCachedTranscript(key, { available: false, reason: "no-captions" });
    expect(getCachedTranscript(key)).toEqual({ available: false, reason: "no-captions" });
  });

  it("REGRESSION (the false-negative bug): an 'unavailable' (fetch-failed) result is NEVER cached at all", () => {
    const key = transcriptCacheKey("wasThrottled1");
    setCachedTranscript(key, { available: false, reason: "unavailable" });
    expect(getCachedTranscript(key)).toBeUndefined();
  });

  it("a confirmed negative expires after its bounded TTL — a later request gets a fresh miss, not a stale 'no'", () => {
    const key = transcriptCacheKey("noCaptions2");
    setCachedTranscript(key, { available: false, reason: "no-captions" });
    expect(getCachedTranscript(key)).toEqual({ available: false, reason: "no-captions" });
    vi.setSystemTime(new Date("2026-08-02T01:00:00.000Z")); // > 24h later
    expect(getCachedTranscript(key)).toBeUndefined();
  });

  it("a positive result never expires, even long after the negative TTL window", () => {
    const key = transcriptCacheKey("longLived1", "en");
    setCachedTranscript(key, positive);
    vi.setSystemTime(new Date("2026-09-01T00:00:00.000Z"));
    expect(getCachedTranscript(key)).toEqual(positive);
  });

  it("different languages for the same video get distinct cache entries", () => {
    const enKey = transcriptCacheKey("sameVideo12", "en");
    const arKey = transcriptCacheKey("sameVideo12", "ar");
    expect(enKey).not.toBe(arKey);
    setCachedTranscript(enKey, { available: false, reason: "no-captions" });
    expect(getCachedTranscript(arKey)).toBeUndefined();
  });

  it("a miss returns undefined, not a thrown error", () => {
    expect(getCachedTranscript(transcriptCacheKey("neverFetched"))).toBeUndefined();
  });

  it("bustCachedTranscript clears a single (videoId, lang) entry for manual re-testing", () => {
    const key = transcriptCacheKey("bustMe1234", "en");
    setCachedTranscript(key, positive);
    expect(getCachedTranscript(key)).toEqual(positive);
    bustCachedTranscript(key);
    expect(getCachedTranscript(key)).toBeUndefined();
  });
});
