"use client";

import { useState } from "react";
import type { TranscriptResult, TranscriptTrack } from "@/lib/transcript";

function formatTimestamp(ms: number): string {
  const totalSec = Math.floor(ms / 1000);
  const min = Math.floor(totalSec / 60);
  const sec = totalSec % 60;
  return `${min}:${sec.toString().padStart(2, "0")}`;
}

/**
 * Collapsible transcript panel — fetches ONLY when opened (never preemptively for the feed/
 * channel/watch-page load), via the server-side `/api/transcript` route so the unofficial
 * timedtext mechanism never runs in the browser. NO CAPTIONS AVAILABLE is a normal, expected
 * outcome, not an error state. See src/lib/transcript.ts for the KNOWN DEVIATION disclosure.
 */
export function TranscriptPanel({ videoId }: { videoId: string }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<TranscriptResult | null>(null);
  const [failed, setFailed] = useState(false);
  const [lang, setLang] = useState<string | undefined>(undefined);

  async function load(requestedLang?: string): Promise<void> {
    setLoading(true);
    setFailed(false);
    try {
      const params = new URLSearchParams({ videoId });
      if (requestedLang) params.set("lang", requestedLang);
      const res = await fetch(`/api/transcript?${params.toString()}`);
      if (!res.ok) {
        setFailed(true);
        return;
      }
      const data = (await res.json()) as TranscriptResult;
      setResult(data);
      if (data.available) setLang(data.languageCode);
    } catch {
      setFailed(true);
    } finally {
      setLoading(false);
    }
  }

  function onToggle(): void {
    const next = !open;
    setOpen(next);
    if (next && result === null && !loading) void load();
  }

  function onLanguageChange(next: string): void {
    setLang(next);
    void load(next);
  }

  return (
    <div className="border-b border-zinc-800 py-4">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={open}
        className="flex w-full items-center justify-between text-left text-sm font-medium text-zinc-300 hover:text-zinc-100"
      >
        <span>Transcript</span>
        <span className="text-zinc-500">{open ? "▲" : "▼"}</span>
      </button>

      {open && (
        <div className="mt-3">
          {loading && <p className="text-sm text-zinc-500">Loading transcript…</p>}

          {!loading && failed && <p className="text-sm text-zinc-500">Transcript unavailable.</p>}

          {!loading && !failed && result && !result.available && (
            <p className="text-sm text-zinc-500">No transcript available for this video.</p>
          )}

          {!loading && !failed && result?.available && (
            <TranscriptBody
              tracks={result.tracks}
              lang={lang}
              cues={result.cues}
              onLanguageChange={onLanguageChange}
            />
          )}
        </div>
      )}
    </div>
  );
}

function TranscriptBody({
  tracks,
  lang,
  cues,
  onLanguageChange,
}: {
  tracks: TranscriptTrack[];
  lang: string | undefined;
  cues: { startMs: number; durMs: number; text: string }[];
  onLanguageChange: (lang: string) => void;
}) {
  return (
    <div>
      {tracks.length > 1 && (
        <select
          value={lang}
          onChange={(e) => onLanguageChange(e.target.value)}
          className="mb-3 rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-1 text-xs text-zinc-300"
        >
          {tracks.map((t) => (
            <option key={t.languageCode} value={t.languageCode}>
              {t.languageName}
              {t.isAutoGenerated ? " (auto-generated)" : ""}
            </option>
          ))}
        </select>
      )}
      <div className="max-h-80 overflow-y-auto rounded-lg bg-zinc-950 p-3 text-sm leading-relaxed text-zinc-300">
        {cues.length === 0 ? (
          <p className="text-zinc-500">No transcript available for this video.</p>
        ) : (
          cues.map((cue, i) => (
            <p key={i} className="mb-1">
              <span className="mr-2 select-none font-mono text-xs text-zinc-600">
                {formatTimestamp(cue.startMs)}
              </span>
              {cue.text}
            </p>
          ))
        )}
      </div>
    </div>
  );
}
